name: todo_getx_isar
version: 1.0.0+1
publish_to: none
description: ToDo App with Getx and Isar
environment: 
  sdk: '>=3.0.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: 5.8.4
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  path_provider: 2.0.15
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  isar_generator: 3.1.0+1
  build_runner: 2.4.5
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

